"""M8 — Provider-independent rainfall ingestion interface.

Every rainfall data source (real radar, synthetic fixture, gauge network,
historical replay) implements this abstract interface. The simulation engine
never hard-codes a specific provider — it receives a RainfallProvider and
queries it for observations.

Each observation carries an explicit source_type:
    REAL       — from a verified operational data source
    SYNTHETIC  — generated by a mathematical model (no real-world claim)
    FIXTURE    — from a static fixture file (deterministic, reproducible)

The frontend/API must always expose source_type; it must never be inferred.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

import numpy as np


class SourceType(str, Enum):
    """Classification of the data source — must appear in every API response."""
    REAL = "REAL"
    SYNTHETIC = "SYNTHETIC"
    FIXTURE = "FIXTURE"


class ProviderStatus(str, Enum):
    """Health status of a rainfall data provider."""
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    UNCONFIGURED = "UNCONFIGURED"


@dataclass(frozen=True)
class RainfallObservation:
    """A single gridded rainfall observation.

    Attributes:
        observation_time: Timestamp of the observation (UTC, timezone-aware).
        valid_from: Start of the validity interval (half-open).
        valid_to: End of the validity interval (half-open).
        rate_mmh: 2-D array of rainfall rates (mm/h). Shape (height, width).
        source_type: REAL / SYNTHETIC / FIXTURE.
        source_name: Human-readable source identifier (e.g. "IMD_Kolkata_Radar").
        source_provider_id: Machine-readable provider identifier.
        spatial_reference: CRS or coordinate reference description.
        spatial_resolution_m: Cell size in metres.
        width: Grid width (cells).
        height: Grid height (cells).
        units: "mm/h" (always).
        quality_flags: List of quality flag strings.
        metadata: Additional provenance metadata.
    """
    observation_time: datetime
    valid_from: datetime
    valid_to: datetime
    rate_mmh: np.ndarray
    source_type: SourceType
    source_name: str
    source_provider_id: str
    spatial_reference: str
    spatial_resolution_m: float
    width: int
    height: int
    units: str = "mm/h"
    quality_flags: tuple[str, ...] = ()
    metadata: dict[str, Any] | None = None

    def __post_init__(self) -> None:
        if self.rate_mmh.ndim != 2:
            raise ValueError("rate_mmh must be 2-D")
        if self.rate_mmh.shape != (self.height, self.width):
            raise ValueError(
                f"rate_mmh shape {self.rate_mmh.shape} != "
                f"({self.height}, {self.width})"
            )
        if np.any(self.rate_mmh < 0):
            raise ValueError("negative rainfall rates are not allowed")
        if not np.all(np.isfinite(self.rate_mmh)):
            raise ValueError("rainfall rates must be finite")
        if self.units != "mm/h":
            raise ValueError(f"units must be 'mm/h', got {self.units!r}")
        if self.observation_time.tzinfo is None:
            raise ValueError("observation_time must be timezone-aware")
        if self.valid_from.tzinfo is None:
            raise ValueError("valid_from must be timezone-aware")
        if self.valid_to.tzinfo is None:
            raise ValueError("valid_to must be timezone-aware")
        if self.valid_to <= self.valid_from:
            raise ValueError("valid_to must be strictly after valid_from")
        if self.metadata is not None:
            import json
            try:
                json.dumps(self.metadata)
            except (TypeError, ValueError) as e:
                raise ValueError("metadata must be JSON-serializable") from e

    def fingerprint(self) -> str:
        """Deterministic fingerprint of this observation.

        Includes a deterministic SHA-256 hash of the complete contiguous
        ``rate_mmh`` array (plus its shape and dtype) so that two rainfall
        fields which share summary statistics (mean/max) but differ in their
        full field are distinguished. Metadata and summary fields are retained.
        """
        import hashlib
        import json
        contiguous_array = np.ascontiguousarray(self.rate_mmh)
        field_hash = hashlib.sha256(contiguous_array.tobytes()).hexdigest()
        payload = {
            "observation_time": self.observation_time.isoformat(),
            "valid_from": self.valid_from.isoformat(),
            "valid_to": self.valid_to.isoformat(),
            "source_type": self.source_type.value,
            "source_provider_id": self.source_provider_id,
            "source_name": self.source_name,
            "quality_flags": list(self.quality_flags),
            "metadata": self.metadata,
            "spatial_reference": self.spatial_reference,
            "spatial_resolution_m": self.spatial_resolution_m,
            "width": self.width,
            "height": self.height,
            "units": self.units,
            "rate_mean_mmh": float(np.mean(self.rate_mmh)),
            "rate_max_mmh": float(np.max(self.rate_mmh)),
            "rate_min_mmh": float(np.min(self.rate_mmh)),
            "field_hash": field_hash,
            "shape": list(self.rate_mmh.shape),
            "dtype": str(self.rate_mmh.dtype),
        }
        canon = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(canon.encode("utf-8")).hexdigest()

    def to_dict(self) -> dict[str, Any]:
        """JSON-safe serialisation (does NOT include the full rate array)."""
        return {
            "observation_time": self.observation_time.isoformat(),
            "valid_from": self.valid_from.isoformat(),
            "valid_to": self.valid_to.isoformat(),
            "source_type": self.source_type.value,
            "source_name": self.source_name,
            "source_provider_id": self.source_provider_id,
            "spatial_reference": self.spatial_reference,
            "spatial_resolution_m": self.spatial_resolution_m,
            "width": self.width,
            "height": self.height,
            "units": self.units,
            "quality_flags": list(self.quality_flags),
            "rate_mean_mmh": round(float(np.mean(self.rate_mmh)), 4),
            "rate_max_mmh": round(float(np.max(self.rate_mmh)), 4),
            "rate_min_mmh": round(float(np.min(self.rate_mmh)), 4),
            "fingerprint": self.fingerprint(),
        }


@dataclass(frozen=True)
class ProviderHealth:
    """Health status of a provider."""
    provider_id: str
    status: ProviderStatus
    source_type: SourceType
    last_observation_time: Optional[datetime]
    message: str
    metadata: dict[str, Any] | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "provider_id": self.provider_id,
            "status": self.status.value,
            "source_type": self.source_type.value,
            "last_observation_time": (
                self.last_observation_time.isoformat()
                if self.last_observation_time else None
            ),
            "message": self.message,
            "metadata": self.metadata or {},
        }


class RainfallProvider(ABC):
    """Abstract base class for all rainfall data providers.

    Every provider must identify itself, expose its health, and return
    observations with explicit provenance. No provider may silently
    substitute synthetic data for missing real data.
    """

    @property
    @abstractmethod
    def provider_id(self) -> str:
        """Machine-readable unique identifier for this provider."""

    @property
    @abstractmethod
    def source_type(self) -> SourceType:
        """REAL / SYNTHETIC / FIXTURE."""

    @property
    @abstractmethod
    def source_name(self) -> str:
        """Human-readable source description."""

    @abstractmethod
    def fetch_latest(self) -> Optional[RainfallObservation]:
        """Return the most recent observation, or None if unavailable.

        Must not silently substitute synthetic data when real data is missing.
        """

    @abstractmethod
    def fetch_observation(self, observation_time: datetime) -> Optional[RainfallObservation]:
        """Return the observation closest to (or at) the given time.

        Must not silently substitute synthetic data when real data is missing.
        """

    @abstractmethod
    def health(self) -> ProviderHealth:
        """Current health status of this provider."""

    @abstractmethod
    def metadata(self) -> dict[str, Any]:
        """Provider metadata (configuration, capabilities, limitations)."""

    @property
    def spatial_reference(self) -> str:
        """Default spatial reference for this provider."""
        return "EPSG:32645"

    @property
    def spatial_resolution_m(self) -> float:
        """Default spatial resolution in metres."""
        return 30.0
